"""Create a robot-icon animation from a real 2D HomeNav-Agent execution trace."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from PIL import ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from interfaces.cli import build_agent
from models.two_d_environment import TwoDHomeEnvironment
from models.two_d_renderer import draw_two_d_map


FPS = 10


class DemoConfig:
    def __init__(self, output_dir: Path) -> None:
        self.values = {
            "llm.model": "mock",
            "llm.temperature": 0,
            "llm.max_tokens": 700,
            "llm.timeout_seconds": 30,
            "system.mode": "two_d",
            "system.max_agent_steps": 12,
            "navigation.max_steps": 200,
            "perception.confidence_threshold": 0.5,
            "memory.db_path": str(output_dir / "demo_memory.db"),
        }

    def get(self, key: str, default: Any = None) -> Any:
        return self.values.get(key, default)


def load_font(size: int, bold: bool = False):
    path = "C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc"
    try:
        return ImageFont.truetype(path, size)
    except OSError:
        return ImageFont.load_default()


def navigation_paths(trace: dict[str, Any]) -> list[list[tuple[int, int]]]:
    paths: list[list[tuple[int, int]]] = []
    for entry in trace.get("tool_history", []):
        if entry.get("tool_name") != "navigation":
            continue
        raw = ((entry.get("observation", {}) or {}).get("data") or {}).get("path") or []
        points = [(int(item["x"]), int(item["y"])) for item in raw if isinstance(item, dict) and "x" in item and "y" in item]
        if points:
            paths.append(points)
    return paths


def add_status(image, text: str) -> None:
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((54, 648, 1224, 699), radius=8, fill="#12355B")
    draw.text((75, 662), text, font=load_font(18, True), fill="#FFFFFF")


def render_frames(environment: TwoDHomeEnvironment, trace: dict[str, Any], result: str) -> list[np.ndarray]:
    frames: list[np.ndarray] = []
    start = TwoDHomeEnvironment.start_cell
    intro = draw_two_d_map(environment, agent_cell=start, title="HomeNav-Agent: 2D Household Task Demo", subtitle="Task: I am thirsty  ->  infer cup  ->  plan A* path  ->  confirm target")
    add_status(intro, "Task received. Agent starts at the hallway and queries household memory.")
    frames.extend([np.asarray(intro)] * 18)
    current = start
    for path_index, path in enumerate(navigation_paths(trace), start=1):
        for step_index, cell in enumerate(path):
            map_image = draw_two_d_map(
                environment,
                agent_cell=cell,
                path=path[: step_index + 1],
                target="杯子",
                title="HomeNav-Agent: 2D Household Task Demo",
                subtitle="Robot icon follows the A* path generated by the Navigation Tool",
            )
            step_text = f"Navigation Tool #{path_index}: moving along A* path ({step_index + 1}/{len(path)} cells)."
            add_status(map_image, step_text)
            frames.append(np.asarray(map_image))
            current = cell
    completed = draw_two_d_map(
        environment, agent_cell=current, path=environment.last_path, target="杯子",
        title="HomeNav-Agent: 2D Household Task Demo", subtitle="Perception confirms the cup; Memory stores the verified position"
    )
    add_status(completed, f"Completed: {result}")
    frames.extend([np.asarray(completed)] * 22)
    return frames


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a 2D map HomeNav-Agent demo video.")
    parser.add_argument("--task", default="I am thirsty", help="Task sent to the real local Agent.")
    parser.add_argument("--output-dir", default="output/two_d_demo", help="Destination for the MP4, map and trace.")
    arguments = parser.parse_args()
    output_dir = Path(arguments.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    agent = build_agent(DemoConfig(output_dir))
    agent.llm.use_mock = True
    agent.llm.client = None
    try:
        result = agent.run(arguments.task)
        trace = agent.get_trace()
        environment = agent.environment
        assert isinstance(environment, TwoDHomeEnvironment)
        map_image = draw_two_d_map(environment, agent_cell=TwoDHomeEnvironment.start_cell, title="HomeNav-Agent: 2D Household Environment", subtitle="Independently constructed two-bedroom household map for discrete navigation validation")
        map_image.save(output_dir / "two_d_household_map.png")
        preview = draw_two_d_map(
            environment,
            agent_cell=environment.agent_cell,
            path=environment.last_path,
            target="\u676f\u5b50",
            title="HomeNav-Agent: Executed 2D Task Trace",
            subtitle="Orange path: actual Navigation Tool trajectory | Green robot: final Agent position",
        )
        add_status(preview, f"Completed: {result}")
        preview.save(output_dir / "task_execution_preview.png")
        frames = render_frames(environment, trace, result)
        height, width = frames[0].shape[:2]
        video_path = output_dir / "HomeNav-Agent_2D_Household_Demo.mp4"
        writer = cv2.VideoWriter(str(video_path), cv2.VideoWriter_fourcc(*"mp4v"), FPS, (width, height))
        if not writer.isOpened():
            raise RuntimeError("Unable to open MP4 writer.")
        try:
            for frame in frames:
                writer.write(cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
        finally:
            writer.release()
        summary = {
            "validation_type": "two_d_discrete_household_environment",
            "task": arguments.task,
            "result": result,
            "tool_sequence": [entry["tool_name"] for entry in trace.get("tool_history", [])],
            "trace": trace,
            "map": "two_d_household_map.png",
            "task_preview": "task_execution_preview.png",
            "video": video_path.name,
            "video_claim": "Robot-icon animation rendered from an actual HomeNav-Agent run on the repository's 2D grid map; not AI2THOR, a camera video, or a physical robot recording.",
        }
        (output_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return 0
    finally:
        closer = getattr(agent.environment, "close", None)
        if callable(closer):
            closer()


if __name__ == "__main__":
    raise SystemExit(main())
